<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EntidadQueResuelve;

class EntidadQueResuelveSeeder extends Seeder
{
    public function run(): void
    {
        $catalogos = [
            'Anestesiologia',
            'Bradford Hill',
            'Broncopulmonar',
            'Cabeza y Cuello',
            'Caiss',
            'Cardiologia',
            'Cecof Chaimavida',
            'Ceredim',
            'Cesfam Boca Sur',
            'Cesfam Carlos Pinto Fierro',
            'Cesfam Chiguayante',
            'Cesfam Hualqui',
            'Cesfam Juan Cartes',
            'Cesfam Juan Soto Fernandez',
            'Cesfam La Leonera',
            'Cesfam Lagunillas',
            'Cesfam Lomas Colorada',
            'Cesfam Lorenzo Arenas',
            'Cesfam Pedro de Valdivia',
            'Cesfam Pinares',
            'Cesfam San Pedro de la Costa',
            'Cesfam San Pedro de la Paz',
            'Cesfam Santa Sabina',
            'Cesfam Sergio Lagos',
            'Cesfam Tucapel',
            'Cesfam Valle La Piedra',
            'Cesfam Victor Manuel Fernandez',
            'Cesfam Villa Nonguen',
            'Cesfam Yobilo',
            'Cesfan Ohiggins',
            'Cirugia Digestiva/Abdominal',
            'Cirugia Infantil',
            'Cirugia Torax',
            'Clinica Alemana',
            'Clinica Andes Salud',
            'Clinica Biobio',
            'Clinica Bupa',
            'Clinica Davila',
            'Clinica Las Condes',
            'Clinica Meds',
            'Clinica Sanatorio Aleman',
            'Clinica Santa Maria',
            'Clinica Universidad Catolica',
            'Clinica Universidad Los Andes',
            'Clinico del Sur',
            'Coloproctologia',
            'Comite Broncopulmonar',
            'Comite Cabeza y Cuello',
            'Comite Cirugia Digestiva',
            'Comite Dermato Oncologico',
            'Comite Endocrino Cyc',
            'Comite Ginecologico',
            'Comite Hematologico',
            'Comite Hepatobiliar',
            'Comite Oncologico',
            'Comite Patologia Mamaria',
            'Comite Proctologico',
            'Comite Radioterapia',
            'Comite Urologico',
            'Compra de Servicio',
            'Coordinadora Red SSC',
            'Coordinadora Red SSC-Hospital Fuera Macrozona Sur',
            'Coordinadora Red SSC-SS Arauco',
            'Coordinadora Red SSC-SS Biobio',
            'Coordinadora Red SSC-SS Ñuble',
            'Coordinadora Red SSC-SS Talcahuano',
            'Coordinadora Red-APS',
            'Cuidados Paliativos',
            'Derivacion',
            'Dermatologia',
            'Destino-HGGB',
            'Endocrinologia',
            'Falp',
            'Finanzas',
            'Gastroenterologia',
            'Genetica',
            'Ges',
            'Gestion Cama',
            'Gestion de la Demanda',
            'Ginecologia',
            'Hematologia',
            'Hepatobiliar',
            'Hggb',
            'Hospital Base de Valdivia',
            'Hospital Clinico Universidad de Chile',
            'Hospital Coronel',
            'Hospital de Talca',
            'Hospital del Salvador',
            'Hospital Florida',
            'Hospital Lota',
            'Hospital Luis Calvo Mackenna',
            'Hospital Santa Juana',
            'Imagenologia',
            'Indicacion',
            'Infectologia',
            'Instituto Nacional Cancer',
            'Iram',
            'Jefe Atencion Abierta/Some',
            'Matrona SSC',
            'Maxilofacial',
            'Medicina Fisica y Rehabilitacion',
            'Medicina Nuclear',
            'Medico Visador',
            'Navegadores en Red',
            'Nefrologia',
            'Neurocirugia',
            'Neurologia',
            'Nutricion',
            'Oftalmologia',
            'Oncohematologia Pediatrica',
            'Oncologia Medica',
            'Oncorad',
            'Otorrinologia',
            'Paciente-Familiar',
            'Patologia Cervical',
            'Patologia Mamaria',
            'Pediatria',
            'Poli Alto Riesgo',
            'Prequirurgica',
            'Psicologo',
            'Psiquiatria',
            'Quemado',
            'Radiologia Intervencional',
            'Radioterapia',
            'Raumatologia',
            'Reclamo',
            'Registro de Tumores',
            'Residencia Oncologica',
            'Reumatologia',
            'Servicio Social Clinico',
            'Subdireccion Redes Complejas',
            'Tens Ugco',
            'Toma de Muestra',
            'Trabajadora Social SSC',
            'Trasplante Solido',
            'Trasportes Urban',
            'Traumatologia',
            'Uc Christus',
            'Udace',
            'Ugco',
            'Urgencia',
            'Urologia'
        ];

        foreach ($catalogos as $catalogo) {
            EntidadQueResuelve::firstOrCreate(['catalogo' => $catalogo]);
        }
    }
}
