<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Requerimiento;

class RequerimientoSeeder extends Seeder
{
    public function run(): void
    {
        $requerimientos = [
            'Ablacion',
            'Alargue residencia conac',
            'Alargue residencia los boldos',
            'Alta bqt',
            'Alta imrt',
            'Alta rt 3d',
            'Alta sbrt',
            'Anoscopia',
            'Aporte economico',
            'Apoyo social',
            'Atencion psicologica',
            'Autorizacion cdex',
            'Biopsia',
            'Braquiterapia',
            'Busqueda contacto telefonico',
            'Cambio de indicacion',
            'Cierre interconsulta',
            'Cintig rama oseo',
            'Cirugia',
            'Colonscopia',
            'Compra de servicio',
            'Contrarreferencia',
            'Control medico',
            'Control nutricionista',
            'Correccion garantia',
            'Cuidados paliativos',
            'Densitometria osea',
            'Derivacion',
            'Dialisis',
            'Dlco',
            'Ebus',
            'Ecocardiograma',
            'Ecografia',
            'Endoscopia digestiva alta',
            'Estudio genetico',
            'Examen de sangre',
            'Examen preoperatorios',
            'Fibrobroncoscopia',
            'Filgastrim',
            'Hipec',
            'Hormonoterapia',
            'Hospitalizacion',
            'Informacion a equipo tratante',
            'Informe medico',
            'Ingreso interconsulta',
            'Ingreso residencia conac',
            'Ingreso residencia los boldos',
            'Kinesioterapia',
            'Mamografia',
            'Mielograma',
            'Movilizacion urbana',
            'Ostomias',
            'Paaf',
            'Pap',
            'Pase',
            'Pet',
            'Pigtail',
            'Presentacion en comite',
            'Procedimiento dermatologico',
            'Protesis',
            'Radioterapia',
            'Receta medicamentos con rt',
            'Rechazo',
            'Reconstitucion',
            'Rectoscopia',
            'Referencia',
            'Reingreso interconsulta',
            'Reingreso residencia conac',
            'Reingreso residencia los boldos',
            'Rescate antecedentes',
            'Rescate imagenes',
            'Resonancia magnetica',
            'Respuesta de comite',
            'Retraso radioterapia',
            'Reunion clinica',
            'Revision ficha clinica',
            'Scanner',
            'Seguimiento',
            'Seguimiento cada 12 meses',
            'Seguimiento cada 3 meses',
            'Seguimiento cada 6 meses',
            'Sin indicacion de tratamiento',
            'Suspension de viaje',
            'Suspension tratamiento',
            'Tace',
            'Traslado de caso',
            'Traslado en ambulancia',
            'Trasplante medula oseas',
            'Tratamiento particular',
            'Tratamiento sistemico',
            'Via de alimentacion',
            'Viaje ida santiago manana',
            'Viaje ida santiago noche',
            'Viaje ida santiago tarde',
            'Viaje ida valdivia manana',
            'Viaje ida valdivia tarde',
            'Viaje ida valdivia noche',
            'Viaje vuelta santiago manana',
            'Viaje vuelta santiago noche',
            'Viaje vuelta santiago tarde',
            'Viaje vuelta valdivia manana',
            'Viaje vuelta valdivia noche',
            'Viaje vuelta valdivia tarde',
            'Visar interconsulta',
            'Visita domiciliaria',
            'Yodoterapia',
        ];

        foreach ($requerimientos as $req) {
            Requerimiento::firstOrCreate([
                'requerimiento' => $req,
                'id_entidad' => rand(1, 140),
                'id_emisor' => rand(1, 140),
                'id_registro_requerimiento' => rand(1, 10),
            ]);
        }
    }
}
