version: '3.8'
services:
  app:
    image: webdevops/php-apache:8.2
    build: null
    container_name: laravel-oncologia-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=sistema_oncologico_docker
      - DB_USERNAME=oncologia_user
      - DB_PASSWORD=oncologia_pass_2025
    depends_on:
      - mysql
    networks:
      - laravel-network